server:
  port: 8080
spring:
  jackson:
    default-property-inclusion: non_null
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 200MB
  profiles:
    active: dev
  application:
    name: start-admin
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 5000
    lettuce:
      pool:
        max-active: 300   #最大连接数据库连接数,设 0 为没有限制
        max-idle: 10     #最大等待连接中的数量,设 0 为没有限制
        max-wait: -1  #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
        min-idle: 5     #最小等待连接中的数量,设 0 为没有限制
      shutdown-timeout: 5000
    database: 0
mamba:
  common:
    env: ${spring.profiles.active}
    port: ${server.port}
    swaggerEnabled: true
    printBeanEnabled: true
