spring:
  redis:
    host: 127.0.0.1
    port: 6379
app:
  cache:
    caffeine-enabled: true # 是否开启caffeine缓存，false则只有redis一级缓存
    caffeine-timeout: 3000 # caffeine缓存过期时间，单位秒，非必填，默认180s
    redis-timeout: 6000 # redis缓存过期时间，单位秒，非必填，默认600s
    sync-enabled: true # 增删改是否需要同步集群中其他机器中的Caffeine
    cacheNamesPackage: com.app.demo.cache.enums # 添加了@CacheNames注解的枚举类package，可为空，空则扫描com.**

